Added metrics
EddieHubCommunity/.github pull request #3
Opened 2021-09-19 11:33 UTC by qwe123coder

I added the yml code for GitHub metrics
@eddiejaoude you would have to create a Personal access tokens from here https://github.com/settings/tokens/new

and then give it admin:org
![image](https://user-images.githubusercontent.com/72848513/133925879-948cd8db-1987-409b-94b8-8a7e814a0936.png)

and make secrets and name it  METRICS_TOKEN

2021-09-20 09:12 UTC, schmelto commented
why removed the profile readme?

2021-09-20 09:36 UTC, eddiejaoude commented
@qwe123coder could you add an example screenshot please

2021-09-20 09:41 UTC, Vyvy-vi reviewed
Thanks for opening this PR!
I had a question- Why was `profile/README.md` deleted, and what's the format for this action? (Can you share a screenshot of what you expect this to output, by running the action on your fork?)

2021-09-20 10:26 UTC, qwe123coder commented
> @qwe123coder could you add an example screenshot please

![screencapture-metrics-lecoq-io-2021-09-20-15_53_37 (1)](https://user-images.githubusercontent.com/72848513/133987967-c8ae773c-f7c4-418a-bab9-a45942f33224.png)

2021-09-21 14:02 UTC, qwe123coder commented
> Thanks for opening this PR!
> I had a question- Why was `profile/README.md` deleted, and what's the format for this action? (Can you share a screenshot of what you expect this to output, by running the action on your fork?)



> > @qwe123coder could you add an example screenshot please
> 
> ![screencapture-metrics-lecoq-io-2021-09-20-15_53_37 (1)](https://user-images.githubusercontent.com/72848513/133987967-c8ae773c-f7c4-418a-bab9-a45942f33224.png)

2021-09-30 12:09 UTC, schmelto commented
I#m not sure if we need this information on the profile readem for the organization. Maybe someone else can share some thoughts.

2021-09-30 12:10 UTC, qwe123coder commented
it will look cool

2021-09-30 15:34 UTC, CodingSpecies commented
@qwe123coder @schmelto I agree it will look good, it uses this link:

https://metrics.lecoq.io/

but if we were going to use this, we might have to disable some of the features, so the README isn't so long. If the readme was long, it wouldn't seem so appealing to viewers, and they might lose interest to seeing what comes after scrolling down the readme(after the readme comes the pinned repos).

That is what I think, but like @schmelto said, we should see what others also think.

2021-10-21 13:03 UTC, Akshu-on-github commented on workflows/readme.yml
> +          config_timezone: Asia/Calcutta
And here too

2021-11-21 05:44 UTC, krishguptadev requested changes
Please check the above comments

2021-11-21 09:19 UTC, closed without merging