add pull request template
EddieHubCommunity/.github pull request #31
Opened 2021-11-27 17:04 UTC by avneesh0612

Resolves #28

2021-11-27 17:13 UTC, krishguptadev approved these changes

2021-12-27 09:39 UTC, syedsohan approved these changes

2022-02-03 14:02 UTC, vikasganiga05 requested changes
LGTM :+1:

2022-02-10 09:41 UTC, KendallDoesCoding approved these changes

2022-03-24 18:27 UTC, vikasganiga05 approved these changes

2022-03-24 21:54 UTC, schmelto approved these changes
Lgtm

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.svg)](https://semasoftware.com/gh) &nbsp;**Summary:** :ok_hand: This code looks good

2022-03-25 03:48 UTC, krshdev approved these changes

2022-03-29 01:07 UTC, merged