Reformed: Profile/README.md
EddieHubCommunity/.github pull request #35
Opened 2021-12-28 13:16 UTC by AnadyaNair

### This pull request introduces the following changes:
- A banner included at the start of the file.
- A description about EddieHub organisation, Eddie's believes, and this place is welcome to all.
- Links redirecting to Eddie's YouTube channel, Eddie's courses, raising issues for joining, Discord community.
- A hello to the mascot - Hubber.
- FAQs discussing 7 topics (redirect links included).

A preview of the reformed README.md can be seen on my [forked repository](https://github.com/AnadyaNair/EddieHubCommunity-.github/blob/main/profile/README.md) for ease.

- [x] Yes, I have read the [Code Of Conduct](https://github.com/EddieHubCommunity/.github/blob/8c3d20d0473adb7f2f7d8d58612f1270ab14e018/CODE_OF_CONDUCT.md).

2021-12-29 18:22 UTC, Pradumnasaraf reviewed
I don't think we need to add that much content to the org page.
`+` For QnA, we have our support repo

Let see what other reviewers think about that :)

2021-12-29 21:00 UTC, CodingSpecies reviewed
@AnadyaNair I think all this detail isn't needed, but you could put it in the support repo. If you have all these details, it may not let the readers move down the organisation home page, and see popular repositories. A simple readme will have a bigger impact. 

## However, I really like the banner! This should be used somewhere in this org!

Thank you.

2021-12-30 04:28 UTC, AnadyaNair commented
Thank you for the reviews!

2022-02-24 13:26 UTC, CodingSpecies requested changes
@AnadyaNair there seems to be conflicts that need resolving thank you.

2022-03-29 02:34 UTC, jonatanlr98 approved these changes

2022-03-29 05:39 UTC, schmelto commented
> I don't think we need to add that much content to the org page.
> 
> `+` For QnA, we have our support repo
> 
> 
> 
> Let see what other reviewers think about that :)
> 
> 

Agree with that

2022-03-31 07:58 UTC, krshdev reviewed
Apart from the FAQ section (which I think should go in the support repo), the rest looks great to me! Please remove the FAQ, Thanks!

__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.svg)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

2022-05-28 19:08 UTC, eddiejaoude commented
Looks good, I think there is too much in bold/big writing - I always recommend adding a small section at a time, so we can continually keep merging things in (little and often is better for you and the project)

2022-07-15 20:26 UTC, CodingSpecies reviewed
Is there any updates on this pr? Thank you.

2025-05-25 06:18 UTC, closed without merging